"""empty message

Revision ID: 523edd94bbda
Revises: f6e62c12b536
Create Date: 2019-03-26 22:21:00.380455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523edd94bbda'
down_revision = 'f6e62c12b536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sold', sa.Column('cgc', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sold', 'cgc')
    # ### end Alembic commands ###
