"""empty message

Revision ID: bdcd463fea60
Revises: 
Create Date: 2019-03-13 00:55:14.402663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdcd463fea60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_table('comicbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.Column('series', sa.String(length=80), nullable=True),
    sa.Column('seriesUpper', sa.String(length=80), nullable=False),
    sa.Column('issueNum', sa.Integer(), nullable=False),
    sa.Column('primaryCharacter', sa.String(length=50), nullable=True),
    sa.Column('primaryVillain', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('authoredBy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authoredBy'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id', 'publisher', 'seriesUpper', 'issueNum')
    )
    op.create_table('selling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date_posted', sa.String(length=10), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['comicbook.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priceSold', sa.Float(), nullable=True),
    sa.Column('dateSold', sa.String(length=10), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['comicbook.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('email_UNIQUE', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email_UNIQUE', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.drop_table('sold')
    op.drop_table('selling')
    op.drop_table('comicbook')
    op.drop_table('author')
    # ### end Alembic commands ###
